/*
 Copyright 2013 Klaviyo, Inc. http://www.klaviyo.com/
*/
(function(x){Array.prototype.toJSON&&delete Array.prototype.toJSON;var m;m||(m={});(function(){function a(a){return 10>a?"0"+a:a}function b(a){f.lastIndex=0;return f.test(a)?'"'+a.replace(f,function(a){var b=k[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,d){var f,k,s,m,n=g,q,l=d[a];l&&"object"===typeof l&&"function"===typeof l.toJSON&&(l=l.toJSON(a));"function"===typeof p&&(l=p.call(d,a,l));switch(typeof l){case "string":return b(l);
case "number":return isFinite(l)?String(l):"null";case "boolean":case "null":return String(l);case "object":if(!l)return"null";g+=h;q=[];if("[object Array]"===Object.prototype.toString.apply(l)){m=l.length;for(f=0;f<m;f+=1)q[f]=c(f,l)||"null";s=0===q.length?"[]":g?"[\n"+g+q.join(",\n"+g)+"\n"+n+"]":"["+q.join(",")+"]";g=n;return s}if(p&&"object"===typeof p)for(m=p.length,f=0;f<m;f+=1)"string"===typeof p[f]&&(k=p[f],(s=c(k,l))&&q.push(b(k)+(g?": ":":")+s));else for(k in l)Object.prototype.hasOwnProperty.call(l,
k)&&(s=c(k,l))&&q.push(b(k)+(g?": ":":")+s);s=0===q.length?"{}":g?"{\n"+g+q.join(",\n"+g)+"\n"+n+"}":"{"+q.join(",")+"}";g=n;return s}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(b){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(a){return this.valueOf()});
var d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,h,k={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},p;"function"!==typeof m.stringify&&(m.stringify=function(a,b,d){var f;h=g="";if("number"===typeof d)for(f=0;f<d;f+=1)h+=" ";else"string"===typeof d&&(h=d);if((p=b)&&"function"!==
typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return c("",{"":a})});"function"!==typeof m.parse&&(m.parse=function(a,b){function c(a,e){var d,f,g=a[e];if(g&&"object"===typeof g)for(d in g)Object.prototype.hasOwnProperty.call(g,d)&&(f=c(g,d),void 0!==f?g[d]=f:delete g[d]);return b.call(a,e,g)}var e;a=String(a);d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof b?c({"":e},""):e;throw new SyntaxError("JSON.parse");})})();var t={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){var b="",c,d,f,g,h,k,p=0;for(a=t._utf8_encode(a);p<a.length;)c=a.charCodeAt(p++),d=a.charCodeAt(p++),f=a.charCodeAt(p++),g=c>>2,c=(c&3)<<4|d>>4,h=(d&15)<<2|f>>6,k=f&63,isNaN(d)?
h=k=64:isNaN(f)&&(k=64),b=b+this._keyStr.charAt(g)+this._keyStr.charAt(c)+this._keyStr.charAt(h)+this._keyStr.charAt(k);return b},decode:function(a){var b="",c,d,f,g,h,k=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");k<a.length;)c=this._keyStr.indexOf(a.charAt(k++)),d=this._keyStr.indexOf(a.charAt(k++)),g=this._keyStr.indexOf(a.charAt(k++)),h=this._keyStr.indexOf(a.charAt(k++)),c=c<<2|d>>4,d=(d&15)<<4|g>>2,f=(g&3)<<6|h,b+=String.fromCharCode(c),64!=g&&(b+=String.fromCharCode(d)),64!=h&&(b+=String.fromCharCode(f));
return b=t._utf8_decode(b)},_utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);128>d?b+=String.fromCharCode(d):(127<d&&2048>d?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b},_utf8_decode:function(a){for(var b="",c=0,d=c1=c2=0;c<a.length;)d=a.charCodeAt(c),128>d?(b+=String.fromCharCode(d),c++):191<d&&224>d?(c2=a.charCodeAt(c+1),b+=String.fromCharCode((d&
31)<<6|c2&63),c+=2):(c2=a.charCodeAt(c+1),c3=a.charCodeAt(c+2),b+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63),c+=3);return b}},c=c||{};c.LEARNING_HOST="a.klaviyo.com";c.LEARNING_DOMAIN="http://www.klaviyo.com";c.JS_VERSION=14;c.DEBUG=!1;c=c||{};c.debug=!1;c.log=function(){var a=new c.Cookie,b=-1<document.location.hash.indexOf("#ldbg");if(c.DEBUG||b||"1"===a.get("learnly_dbg"))(b=x.console)&&"function"===typeof b.log&&b.log.apply(b,arguments),a.set("learnly_dbg","1")};c=c||{};c.global={};c.global.Context=
function(a,b,c,d,f,g,h){this.doc=a||document;this.nav=b||navigator;this.scr=c||screen;this.win=d||x;this.loc=f||this.doc.location;this.top=g||top;this.parent=h||parent};c.global.Context.prototype.getDocument=function(){return this.doc};c.global.Context.prototype.getNavigator=function(){return this.nav};c.global.Context.prototype.getScreen=function(){return this.scr};c.global.Context.prototype.getWindow=function(){return this.win};c.global.Context.prototype.getLocation=function(){return this.loc};
c.global.Context.prototype.getProtocol=function(){return"https:"==this.loc.protocol?"https://":"http://"};c.global.Context.prototype.getHostName=function(){return this.loc.hostname};c.global.Context.prototype.getTop=function(){return this.top};c.global.Context.prototype.getParent=function(){return this.parent};c.global.Context.prototype.getReferrer=function(){var a="";try{a=this.top.document.referrer}catch(b){if(parent)try{a=this.parent.document.referrer}catch(c){a=""}}""===a&&(a=this.doc.referrer);
return a};c.global.Context.prototype.getCharacterSet=function(){return this.doc.characterSet?this.doc.characterSet:this.doc.charset?this.doc.charset:""};c.global.Context.prototype.getLanguage=function(){return this.nav.language?this.nav.language:this.nav.browserLanguage?this.nav.browserLanguage:""};c.global.Browser=function(a){var b=(a||new c.global.Context).getNavigator();a=b.userAgent.toLowerCase();var e={init:function(){this.browser=this.searchString(this.dataBrowser)||"";this.version=this.searchVersion(b.userAgent)||
this.searchVersion(b.appVersion)||"";this.OS=this.searchString(this.dataOS)||""},searchString:function(a){for(var b=0;b<a.length;b++){var c=a[b].string,e=a[b].prop;this.versionSearchString=a[b].versionSearch||a[b].identity;if(c){if(-1!=c.indexOf(a[b].subString))return a[b].identity}else if(e)return a[b].identity}},searchVersion:function(a){var b=a.indexOf(this.versionSearchString);if(-1!=b)return parseFloat(a.substring(b+this.versionSearchString.length+1))},dataBrowser:[{string:b.userAgent,subString:"Chrome",
identity:"Chrome"},{string:b.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:b.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{prop:x.opera,identity:"Opera"},{string:b.vendor,subString:"iCab",identity:"iCab"},{string:b.vendor,subString:"KDE",identity:"Konqueror"},{string:b.userAgent,subString:"Firefox",identity:"Firefox"},{string:b.vendor,subString:"Camino",identity:"Camino"},{string:b.userAgent,subString:"Netscape",identity:"Netscape"},{string:b.userAgent,
subString:"MSIE",identity:"Internet Explorer",versionSearch:"MSIE"},{string:b.userAgent,subString:"Gecko",identity:"Mozilla",versionSearch:"rv"},{string:b.userAgent,subString:"Mozilla",identity:"Netscape",versionSearch:"Mozilla"}],dataOS:[{string:b.platform,subString:"Win",identity:"Windows"},{string:b.platform,subString:"Mac",identity:"Mac"},{string:b.userAgent,subString:"iPhone",identity:"iPhone/iPod"},{string:b.platform,subString:"Linux",identity:"Linux"}]};e.init();this.version=(a.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||
[0,"0"])[1];this.os=e.OS;this.browser=e.browser};c=c||{};c.utils=c.utils||{};var y={},r=Array.prototype,v=Object.prototype,F=r.slice,z=v.toString,G=v.hasOwnProperty,C=r.forEach,D=r.indexOf,E=r.some;c.utils.isArray=Array.isArray||function(a){return"[object Array]"==z.call(a)};c.utils.isUndefined=function(a){return void 0===a};c.utils.has=function(a,b){return G.call(a,b)};var w=c.utils.each=function(a,b,e){if(null!=a)if(C&&a.forEach===C)a.forEach(b,e);else if(a.length===+a.length)for(var d=0,f=a.length;d<
f&&!(d in a&&b.call(e,a[d],d,a)===y);d++);else for(d in a)if(c.utils.has(a,d)&&b.call(e,a[d],d,a)===y)break};c.utils.identity=function(a){return a};var H=c.utils.any=function(a,b,e){b||(b=c.utils.identity);var d=!1;if(null==a)return d;if(E&&a.some===E)return a.some(b,e);w(a,function(a,c,h){if(d||(d=b.call(e,a,c,h)))return y});return!!d};c.utils.contains=function(a,b){var c=!1;return null==a?c:D&&a.indexOf===D?-1!=a.indexOf(b):c=H(a,function(a){return a===b})};c.utils.extend=function(a){w(F.call(arguments,
1),function(b){for(var c in b)a[c]=b[c]});return a};var A=function(a,b,e){if(a===b)return 0!==a||1/a==1/b;if(null==a||null==b)return a===b;var d=z.call(a);if(d!=z.call(b))return!1;switch(d){case "[object String]":return a==String(b);case "[object Number]":return a!=+a?b!=+b:0==a?1/a==1/b:a==+b;case "[object Date]":case "[object Boolean]":return+a==+b;case "[object RegExp]":return a.source==b.source&&a.global==b.global&&a.multiline==b.multiline&&a.ignoreCase==b.ignoreCase}if("object"!=typeof a||"object"!=
typeof b)return!1;for(var f=e.length;f--;)if(e[f]==a)return!0;e.push(a);var f=0,g=!0;if("[object Array]"==d){if(f=a.length,g=f==b.length)for(;f--&&(g=f in a==f in b&&A(a[f],b[f],e)););}else{if("constructor"in a!="constructor"in b||a.constructor!=b.constructor)return!1;for(var h in a)if(c.utils.has(a,h)&&(f++,!(g=c.utils.has(b,h)&&A(a[h],b[h],e))))break;if(g){for(h in b)if(c.utils.has(b,h)&&!f--)break;g=!f}}e.pop();return g};c.utils.isEqual=function(a,b){return A(a,b,[])};c.utils.url=function(a){return(c.DEBUG?
"http://":(new c.global.Context).getProtocol())+c.LEARNING_HOST+"/"+a};c.utils.encodeParam=function(a,b){var c=encodeURIComponent;return c instanceof Function?b?encodeURI(a):c(a):escape(a)};c.utils.encodeParams=function(a,b){var e=[];b=b||"&";var d=function(a,b){e[e.length]=c.utils.encodeParam(a)+"="+c.utils.encodeParam(b)};w(a,function(a,b){c.utils.isArray(a)?w(a,function(a,c){d(b,a)}):d(b,a)});return e.join(b).replace(/%20/g,"+")};c.utils.decodeParam=function(a,b){var c=decodeURIComponent,d;a=a.split("+").join(" ");
if(c instanceof Function)try{d=b?decodeURI(a):c(a)}catch(f){d=unescape(a)}else d=unescape(a);return d};c.utils.addEventListener=function(a,b,c,d){if(a.addEventListener)return a.addEventListener(b,c,d),!0;if(a.attachEvent)return a.attachEvent("on"+b,c);a["on"+b]=c};c.utils.hashDomain=function(a){for(var b=0,c=a.length-1;0<=c;c--)var d=a.charCodeAt(c),b=(b<<6&268435455)+d+(d<<14),d=b&266338304,b=0!=d?b^d>>21:b;return b};c.utils.extractDomain=function(a){a=a.split(".");2<a.length&&(a=a.slice(1));return"."+
a.join(".")};c.utils.utcnow=function(){var a=new Date,b=a.getTime(),a=6E4*a.getTimezoneOffset();return Math.round((b+a)/1E3)};c.utils.utf8Encode=function(a){a=(a+"").replace(/\r\n/g,"\n").replace(/\r/g,"\n");var b="",c,d,f=0,g;c=d=0;f=a.length;for(g=0;g<f;g++){var h=a.charCodeAt(g),k=null;128>h?d++:k=127<h&&2048>h?String.fromCharCode(h>>6|192)+String.fromCharCode(h&63|128):String.fromCharCode(h>>12|224)+String.fromCharCode(h>>6&63|128)+String.fromCharCode(h&63|128);null!==k&&(d>c&&(b+=a.substring(c,
d)),b+=k,c=d=g+1)}d>c&&(b+=a.substring(c,a.length));return b};c.utils.logError=function(a,b){b=b||{};var e={ts:c.utils.utcnow(),m:a.message||a.toString?a.toString():"-",v:c.JS_VERSION};c.utils.extend(e,b);a.name&&(e.n=a.name);a.fileName&&(e.f=a.fileName);a.lineNumber&&(e.l=a.lineNumber);try{e.x=a.stack||a.stacktrace||""}catch(d){}c.log("Encountered a JS error");c.log(e)};c=c||{};c.Cookie=function(a){this.context=a||new c.global.Context;this.cookies=[]};c.Cookie.prototype.set=function(a,b,e){e=e||
{};var d;e.minsToExpire?(d=new Date,d.setTime(d.getTime()+6E4*e.minsToExpire)):e.daysToExpire&&(d=new Date,d.setTime(d.getTime()+864E5*e.daysToExpire));this._set(a,e.alreadyEncoded?b:c.utils.encodeParam(b,!0),(c.utils.isUndefined(d)?"":";expires="+d.toGMTString())+";path="+(e.path?e.path:"/")+(e.domain?";domain="+e.domain:"")+(e.secure?";secure":""))};c.Cookie.prototype._set=function(a,b,c){this.context.getDocument().cookie=a+"="+b+c;this.cookies.push({name:a,value:b,extras:c})};c.Cookie.prototype.get=
function(a){return(a=RegExp("(^|;)[ ]*"+a+"=([^;]*)").exec(this.context.getDocument().cookie))?c.utils.decodeParam(a[2],!0):""};c.Cookie.prototype.del=function(a,b){b=b||{};b.daysToExpire=-1;this.get(a)&&this.set(a,"",b)};c.Cookie.prototype.has=function(){return c.utils.isUndefined(this.context.getNavigator().cookieEnabled)?this.context.getNavigator().cookieEnabled?"1":"0":(this.set("__l_testcookie","1"),"1"==this.get("__l_testcookie")?"1":"0")};c=c||{};c.LocalStorage=function(a){this.context=a||
new c.global.Context;this.is_available=!1;try{return localStorage.setItem("_kla_test","_kla_test"),localStorage.removeItem("_kla_test"),this.is_available=!0}catch(b){}};c.LocalStorage.prototype.set=function(a,b){if(!this.is_available)return!1;localStorage.setItem(a,b);return!0};c.LocalStorage.prototype.get=function(a){if(this.is_available)return localStorage.getItem(a)};c.LocalStorage.prototype.del=function(a){if(!this.is_available)return!1;localStorage.removeItem(a);return!0};c.tracking=c.tracking||
{};c.tracking.Tracker=function(a){this.context=a.context;this.cookie=a.cookie;this.local_storage=a.local_storage;this.identity=this.cookie_domain=this.account_id=null;this.has_tracked_interests=this.has_tracked_activity=!1;this.is_tracking_on=!this.cookie.get("__kla_off");if(a=this.cookie.get("__kla_id"))try{this.identity=m.parse(t.decode(a))}catch(b){}};c.tracking.Tracker.prototype.account=function(a){this.is_tracking_on&&!c.utils.isUndefined(a)&&(this.account_id=a);return this.account_id};c.tracking.Tracker.prototype.cookieDomain=
function(a){this.is_tracking_on&&!c.utils.isUndefined(a)&&(this.cookie_domain=a);return this.cookie_domain};c.tracking.Tracker.prototype.identify=function(a,b,e){if(!1===b&&this.identity||!this._identityNeedsUpdate(a)||!this.account_id)return this.identity;var d=c.utils.extend({},this.identity,a);this._sendRequest({url:"api/identify",data:{data:t.encode(m.stringify({token:this.account_id,properties:d}))}});c.utils.each(["$append","$unappend","$unset"],function(a){c.utils.has(d,a)&&(c.utils.each(d[a],
function(b,e){"$unset"===a&&(e=b);c.utils.has(d,e)&&delete d[e]}),delete d[a])});!1!==e&&this._setIdentity(d);this.trackActivity();return d};c.tracking.Tracker.prototype.clearIdentity=function(){this.cookie.del("__kla_id");this.identity=null};c.tracking.Tracker.prototype.trackActivity=function(){if(!this.has_tracked_activity){this._saveReferrer();this._parseInitialUrl();var a=this.context,b=new c.global.Browser(a),a={page:a.getLocation().href,browser:b.browser,os:b.os};this.track("__activity__",a)&&
(this.has_tracked_activity=!0)}};c.tracking.Tracker.prototype.trackInterests=function(){if(!this.has_tracked_interests){this._saveReferrer();this._parseInitialUrl();var a={$tags:this._parsePageTags()};this.track("$passive_interest",a)&&(this.has_tracked_interests=!0)}};c.tracking.Tracker.prototype.trackViewedItem=function(a){if(this.local_storage.is_available){var b=c.utils.utcnow(),e=this.local_storage.get("__kla_viewed");try{e=m.parse(e)||[]}catch(d){e=[]}if(e.length){var f;c.utils.each(e,function(a){a[0].LastViewedDate&&
(!f||a[0].LastViewedDate>f)&&(f=a[0].LastViewedDate)});if(!f||f+2592E3<b)e=[]}var g=!1;c.utils.each(e,function(c){if(a.ItemID===c[0].ItemID)return c[1]++,c[0].LastViewedDate=b,g=!0,!1});g||(a.LastViewedDate=b,e.unshift([a,1]),e=e.splice(0,20));e.sort(function(b,c){return b[1]!==c[1]?c[1]-b[1]:b[0].ItemID===a.ItemID?-1:c[0].ItemID===a.ItemID?1:0});this.local_storage.set("__kla_viewed",m.stringify(e));var h={},k=[];c.utils.each(e,function(a){normalized_item=c.utils.extend({},a[0]);normalized_item.Views=
a[1];k.push(normalized_item)});h.$viewed_items=k;this.identify(h,!0,!1)}};c.tracking.Tracker.prototype.track=function(a,b){b=b||{};var c=this.account_id,d=this.identity||{};if(!c||!(d.email||d.id||d.$email||d.$id))return!1;b.$use_ip=!0;b.$is_session_activity=!0;this._sendRequest({url:"api/track",data:{data:t.encode(m.stringify({event:a,token:c,properties:b,customer_properties:d}))}});return!0};c.tracking.Tracker.prototype.trackOnce=function(a,b){b=c.utils.extend({__track_once__:!0},b);return this.track(a,
b)};c.tracking.Tracker.prototype._identityNeedsUpdate=function(a){var b=this.identity;a=c.utils.extend({},b,a);return!b||!c.utils.isEqual(b,a)};c.tracking.Tracker.prototype._setIdentity=function(a){this.identity=a;this._saveIdentity(a)};c.tracking.Tracker.prototype._saveIdentity=function(a){this.cookie.set("__kla_id",t.encode(m.stringify(a)),{daysToExpire:730,domain:this.cookie_domain})};c.tracking.Tracker.prototype._saveReferrer=function(){var a=c.utils.extend({},this.identity);a.$referrer||(a.$referrer=
{ts:c.utils.utcnow(),value:this.context.getReferrer(),first_page:this.context.getLocation().href},this._setIdentity(a))};c.tracking.Tracker.prototype._parseInitialUrl=function(){var a=this.context.getLocation(),b=a.search.match(/utm_email=([^#&]+)/i);b&&this.identify({$email:decodeURIComponent(b[1])});(b=a.search.match(/_ke=([^#&]+)/i))&&this.identify({$email:t.decode(decodeURIComponent(b[1]))})};c.tracking.Tracker.prototype._parsePageTags=function(){var a=this,b=document.getElementsByTagName("meta"),
e,d;c.utils.each(b,function(b){var c=b.getAttribute("name");b.getAttribute("property");"keywords"===c?d||(b=a._normalizeTags(b.getAttribute("content")))&&b.length&&(d=b):"klaviyo:tags"!==c||e||(b=a._normalizeTags(b.getAttribute("content")))&&b.length&&(e=b)});return e&&e.length?e:d&&d.length?d:!1};c.tracking.Tracker.prototype._normalizeTags=function(a){if(null===a)return[];a=c.utils.isArray(a)?a:a.split(",");for(var b=0,e=a.length,d=[],f;b<e;b++)(f=a[b].toLowerCase().replace(" ","-").replace("_",
"-").replace(/[^a-z\-]/gi,"").replace(/^(-)*/,"").replace(/(-)*$/,"").substring(0,64))&&!c.utils.contains(d,f)&&d.push(f);return d};c.tracking.Tracker.prototype._sendRequest=function(a,b){c.log("Sending request.");a.data.i=1;a&&c.log(a);var e=c.utils.url(a.url),e=e+"?"+c.utils.encodeParams(a.data);c.log(e);var d=new Image(1,1);b&&(d.onload=function(){b()});d.src=e};var r=new c.global.Context,v=r.getWindow(),n=v._learnq,u=new c.tracking.Tracker({cookie:new c.Cookie(r),local_storage:new c.LocalStorage(r),
context:r});if(!n||!n._loaded){var B=function(a){if("function"==typeof a)a(u,c);else if(c.utils.isArray(a)&&a&&u[a[0]])return u[a[0]].apply(u,a.slice(1))};c.utils.isArray(n)||(v._learnq=[],n=v._learnq);c.log("Ready. Processing LEARNQ2.");for(c.utils.each(n,function(a){c.utils.isArray(a)&&a&&c.utils.contains(["account","cookieDomain","identify"],a[0])&&B(a)});n.length;)B(n.shift());n.push=B;c.utils.each(["account","cookieDomain","identify","track"],function(a){u[a]&&(n[a]=function(){return u[a].apply(u,
arguments)})});n._loaded=!0;n.push(["trackActivity"])}})(window);
